apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: workflows
spec:
  encryptedData:
    .dockerconfigjson: AgBeO+gcgDQJajJ6BU7kA05kG+Oft+8I40drF0sUwS2VkEUwl6Ul+PU3OcCGu6eLazHZRxd1vmbzlf8ek6Cyr42fO2hg9riSPrTw0Ui6/nwfzUACMvdCDNJcBt26RzQlCgLyID4qrTRv1qGThbnDgRDaICyddjAM/qf62jVMElhbHWzH3oUejuLGnBUXkRo5tYYsvVm7ptY3DWzL+PnLXsXxpyr/ixqHFrHC1djI9VV1Bf6QtnhK5JqvRAxWSqiXxWa6Tj7Tb0RgqDlsWZR4qzG6hcTiHXe5ae8OnB01+w5ToCt+I36QZuFTGRDS/jpyvVNy4E7R+qgTiZERWwG9dtL85yJYKUL8LXaS2UsevU51WrlZ/woSf6AogzwDFX213vfPq2L2yBlmEPpbXNMgfWAgcPPSfqeZtfQ9AgemAba2n+KDh++8vTSQmUxdwogarS0q+NoU5S2yDL2TmnFT7R/X4DMG4G1yZLr2BHjJUEl04A73/PtYqZBJbWP/3T0Yc2r+a2DlUF3cfX5xP7eAWkpgsYTZISxmHhHJO2g9mqGhYpbm0xoGDE4+0dP6gkaDY6iSuKylq0COKicJaWGlIEb29zfSYhIZuPA8pA4UoXpVSB9JjDVbMcbpm9hV9O9xx0HoqQahuJ2dEin9dcrDnPa5NQjesfyJNcOz4uupegQrnMct273G+dF1uee9z9Q3b+h8oZ1t7RWaG0UCNadop/tkg2R/h4wJZ030FpZCj0toCbzBLAO8NThoXsDSABUm0IiQEy2Ayna7VpOwdCO/LJI7NOk64OcKUPg5gvXoyzYMGNqdV61RMxbmnj0cfEMCxt5ZyHislPZ/yF3nx2TXDhlVPe8fHzvysZP67DVIUFu4zdmx28RNesfAVu0Z9mP8aXRbGRtyd5MkJIYLFbEiNNVycKqljyTXpMOa8/Wf2L71g+/3GGEADfS8dPeL2ICiWa2euCzshRywEZ+1D/2mPt1jNZFqBlBDCdwnckjRDA==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: workflows
    type: kubernetes.io/dockerconfigjson

