apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access
  namespace: argo-events
spec:
  encryptedData:
    token: AgCPovpIGzXvrf8jFmu4IJTxB/oqGiPr1gEoHlMrAkPhRccKJVgT8N9RiLc+nVSmoQZ+CxHUcJU88U1JvpFSCnuFJgA6ReBFEnMlfTY9WmwaYvnv2oj3G0DD1GChrU5x7+QeSVcejTcSJjVOc2LyPvfJG4TpqE3/4npGjcY4C0VZeuknrzpcMnsWeQz+Jn7OV/o3s3QMR+Vg8P8i9oRoIafY5I6EpL+aySXbczIrWRoGoygiwxAZvMaEIOVBSCwtnEfY0Po+VHcKsHZ1VVqsw7mqFqOBPRa/n67rpyQ4Ya7HByC7mvX8B5Wq2+TKOn17Zuq1P4CgGIEyeVaP+GQUtr5TskEHy/TpqW7/Ps2NYmNtcno+bW2stLxdJZurQUlyb8oZiVTct7jL7V4lHsDejDA/06x67z+bxAFf98jzMntgXaFsXZwMXRbmO9V7P8EPjn5D++pH9Q8DoYeE0R58ZiI1+YfZUGGJjfSjdu8sTL7PqYeeb/DjNZGlMA7yOtHKeD/UDCe4qQhEdz9y+a+D3V38DVRK+gZs5NKhDDolkMDK9u/9BIVpx1/3gUXWBGT29ZmP836xS7qG3nN7xC42ciio/2wuehKsxK8IiQRk/fZTRealiBdl/Bgnhy01aH/UXRjg3wx9AVNQudC7RVzIHnERSpvyl13yInvc17FklrBjgc+w038vS3N1CN+RO/O1+C3j0sDFSvZCKGbbaRUp0ibDr2+v9gTed2GGoZ51cRyrVc6pyayXbcX+
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: github-access
      namespace: argo-events
    type: Opaque

