apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access
  namespace: argo-events
spec:
  encryptedData:
    token: AgBriMFh4O/jTbeystLptS7F281LAAJx1EFB6HM8U9BE+18qCwAnwAWTq1QgnL5AYpeSiLCexLhSRVdfz9Z2xDwMh6Ampm+yvT3k+ojnkmYW91+AiyWYvR7hoEwBuc/u6d1tal5DcTumvTJFtRBeC3yMqqOguVcFk4RovuAZsHqgIMZ89ocBUh+I9oBNTn+tMCC855Pks9iWouzL33hBsJxpjZ7ekAxDPC6Pz6G7ijcpsb0CUvg38gMYWwOnXK3curo4drqjQytkJ//ghSQKRk9A0D8j9Cu1HqjwH46Cqibx5AmyAg6H9vL8u8KWkah3+89VySSkNtLQCxPclbweh82RsvS7EUDOBCc4AQjAn8IGuN2nb+flU0Hh5+mQ4hh2cojjrnIZzgu1IaD504kWCim1QFa+sCtQdO7O62ewKQvJn3T8xoxtk79zOOHm9mfkcZ/7yLxHOyCdB944dKnMJ5S+1X8HTOndKtxNYO+Xq3LEpLjznz/NNC5noCi2ejOzs6i3QfilrBCQSXpfO1MVMP3Thfk1gvx9TPfamDPY6DR0oolYzPy/QQeIVQUuHqRuOaHPvDMlY1pJcOfcyorU7RxI3AG9VbhSy8GgxIDVocRXj+AbBSom0cTez/evy9DfBUjZmcJDneNDEnzVdrBog3E1dFNbDW+4gHhvAfE7SdEPeuxSPXeeJsjZWXEJX5AcV0Q=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: github-access
      namespace: argo-events
    type: Opaque

